- name: Check if CFM Operator version is already downloaded
  stat:
    path: /tmp/cfmctl
  register: cfmctl_stat
  changed_when: false
  failed_when: false

- name: Set environment variables for Cloudera credentials
  become_user: "{{ ansible_user }}"
  set_fact:
    env_vars:
      Cloudera_username: "{{ Cloudera_username }}"
      Cloudera_password: "{{ Cloudera_password }}"

- name: Log in to Cloudera registry using Helm
  become_user: "{{ ansible_user }}"
  shell: |
    echo "{{ Cloudera_password }}" | helm registry login container.repository.cloudera.com \
    --username "{{ Cloudera_username }}" \
    --password-stdin

- name: Copy Cloudera license file to remote host
  become_user: "{{ ansible_user }}"
  copy:
    src: cloudera_license.txt
    dest: /tmp/cloudera_license.txt
    mode: '0600'

- name: Create license secret for CFM Operator
  become_user: "{{ ansible_user }}"
  shell: |
    kubectl create secret generic cfm-operator-license \
      --from-file=license.txt=/tmp/cloudera_license.txt \
      -n cfm-operator-system \
      --dry-run=client -o yaml | kubectl apply -f -
  register: license_secret_create
  failed_when: license_secret_create.rc != 0
  changed_when: "'created' in license_secret_create.stdout or 'configured' in license_secret_create.stdout"

- name: Download cfmctl binary
  shell: >
    curl -u "{{ Cloudera_username }}:{{ Cloudera_password }}" \
      -o cfmctl-linux-amd64 https://archive.cloudera.com/p/cfm-operator/cfmctl-linux-amd64
  args:
    chdir: /tmp
  when: cfmctl_stat.stat.exists == false  # Only download if not already present
  failed_when: false
  changed_when: true

- name: Make cfmctl executable and rename it
  ansible.builtin.shell: |
    chmod +x cfmctl-linux-amd64
    mv cfmctl-linux-amd64 cfmctl
  args:
    chdir: /tmp
  when: cfmctl_stat.stat.exists == false 
  failed_when: false  # handle extraction issue as needed
  changed_when: true

- name: Check if CFM Operator is already installed via Helm
  become_user: "{{ ansible_user }}"
  shell: helm list -n cfm-operator-system --filter ^cfm-operator$ | grep cfm-operator || true
  register: cfm_operator_installed
  changed_when: false
  failed_when: false

- name: Install CFM Operator via cfmctl if not already installed
  become_user: "{{ ansible_user }}"
  shell: |
    ./cfmctl install \
    --license ./cloudera_license.txt \
    --image-repository container.repository.cloudera.com/cloudera/cfm-operator \
    --image-tag {{ cfm_operator_version }} \
    --namespace cfm-operator-system
  args:
    chdir: /tmp
  when: cfm_operator_installed.stdout == ""
  register: install_cfm_operator_result
  changed_when: "'has been added' in install_cfm_operator_result.stdout"

- name: Wait for pods to be running in cfm-operator-system namespace
  become_user: "{{ ansible_user }}"
  shell: |
    kubectl get pods -n cfm-operator-system | grep -E 'cfm-operator' | awk '{print $3}' | grep -v 'Running'
  register: pod_status
  until: pod_status.stdout == ""
  retries: 10
  delay: 30
  failed_when: false

- name: Apply NiFi configuration
  become_user: "{{ ansible_user }}"
  shell: kubectl apply -f /tmp/nifi_overrides.yaml -n demo-nifi
  register: nifi_apply
  changed_when: "'created' in nifi_apply.stdout or 'configured' in nifi_apply.stdout"
  failed_when: nifi_apply.rc != 0

- name: Apply NiFi Registry configuration
  become_user: "{{ ansible_user }}"
  shell: kubectl apply -f /tmp/nifiregistry.yaml -n demo-nifi-registry
  register: nifi_registry_apply
  changed_when: "'created' in nifi_registry_apply.stdout or 'configured' in nifi_registry_apply.stdout"
  failed_when: nifi_registry_apply.rc != 0
